sudo: required

language: scala

scala:
  - 2.11.6

services:
  - docker

env:
  global:
    - TERM=dumb

notifications:
  email: false

install: true

before_install:
  - openssl aes-256-cbc -K $encrypted_ff5bbb6225c5_key -iv $encrypted_ff5bbb6225c5_iv -in tests/credentials.json.enc -out tests/credentials.json -d
  - git clone https://github.com/openwhisk/openwhisk.git
  - cd openwhisk
  - ./tools/travis/setup.sh

script:
  - ../tools/travis/build.sh
